import sys
import os

introduction = '''/*
 * this file is automatically generated by process_lua_files.py
 */
'''
write_dir = "main"
read_dir = "main/modules/behaviors"

def build_header_file():
    with open(f"{write_dir}/.lua_files.h", "w") as file:
        file.write(introduction)
        file.write('''
#ifndef _LUA_FILES_H_
#define _LUA_FILES_H_

#include "hugo_error.h"
HUGO_RET_VAL create_lua_files();

#endif //_LUA_FILES_H_
''');

def process_dir(path):
    out_paths = list()
    entries = os.listdir(path);
    for entry in entries:
        new_path = path + "/" + entry
        if os.path.isdir(new_path):
            out_paths += process_dir(new_path)
        if os.path.isfile(new_path):
            out_paths.append(new_path[len(read_dir) + 1: ])
    return out_paths

def get_body_entry(path):
    file_name = os.path.basename(path).replace(".", "_")
    indent = "    "
    out = ""
    out += f'{indent}extern const char {file_name}_start[] asm("_binary_{file_name}_start");\n'
    out += f'{indent}extern const char {file_name}_end[]   asm("_binary_{file_name}_end");\n'
    out += f'{indent}init_file("/lua/{path}", {file_name}_start, {file_name}_end);\n'
    return out

def get_body():
    file_paths = process_dir(read_dir)
    body = ""
    for path in file_paths:
        body += "\n" if body else ""
        body += get_body_entry(path)
    body += "return HUGO_OK;\n"
    return body

def get_init_file():
    return '''
void init_file(const char * file_name, const char * data_start, const char * data_end)
{
    static const char *TAG = "LUA_FILES";
    if( access(file_name, F_OK ) != -1 ) {
        ESP_LOGI(TAG, "file %s already exists", file_name);
    }
    else{
        ESP_LOGI(TAG, "file %s will be created", file_name);
        FILE *f = fopen(file_name, "wb");

        if (f == NULL) {
            ESP_LOGE(TAG, "Failed to open file for writing");
            return;
        }
        fwrite(data_start, sizeof(char), data_end - data_start - 1, f);
        fclose(f);
    }
}

'''

def get_c_includes():
    return '''
#include ".lua_files.h"
#include <unistd.h>
#include "esp_err.h"
#include "esp_log.h"
'''
def build_source_file():
    with open(f"{write_dir}/.lua_files.c", "w") as file:
        file.write(introduction)
        file.write(get_c_includes())
        file.write(get_init_file())
        file.write(("HUGO_RET_VAL create_lua_files()\n{\n"))
        file.write(get_body())
        file.write(("}\n"))


build_header_file()
build_source_file()
