#pragma once

#define I2C_COMMAND_RGB_SET_RGB 1 // followed by 3 bytes (RGB)
#define I2C_COMMAND_RGB_SET_COLOR 2
#define I2C_COMMAND_RGB_SET_ON 3
#define I2C_COMMAND_RGB_SET_OFF 4

#define RGB_LED_CLOLOR_BLACK 1
#define RGB_LED_CLOLOR_WHITE 2
#define RGB_LED_CLOLOR_RED 3
#define RGB_LED_CLOLOR_GREEN 4
#define RGB_LED_CLOLOR_BLUE 5
#define RGB_LED_CLOLOR_YELLOW 6
#define RGB_LED_CLOLOR_PURPLE 7
#define RGB_LED_CLOLOR_CYAN 8
#define RGB_LED_CLOLOR_ORANGE 9
#define RGB_LED_CLOLOR_GREENYELLOW 10
#define RGB_LED_CLOLOR_SKYBLUE 11
#define RGB_LED_CLOLOR_AQUAMARINE 12
#define RGB_LED_CLOLOR_MAGENTA 13
#define RGB_LED_CLOLOR_VIOLET 14